version: '4'
services:
  product-service:
    image: mongo:7.0.5
    container_name: mongodb-product-service
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: product-service